"""Deterministic builders for the Global Market Pulse tests.

Every helper here is network-free and clock-free. A test that needs a market
that rose, fell, went nowhere or could not be read builds it from these rather
than from a provider, so the whole suite is a pure function of its own source.

**Prices are generated by an explicit rule, never randomly.** A random series
makes a failing assertion unreproducible and makes a mutation survivor
impossible to attribute. `linear_klines` walks a stated step, so every expected
figure in the suite can be derived by hand.
"""

from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone

from fmis.data import Candle, CandleSeries
from fmis.data.observation import ObservationSeries
from fmis.market_pulse import (
    Benchmark,
    MarketCategory,
    MarketUniverse,
    ProviderInstrument,
    TradingSchedule,
)
from fmis.providers.binance import HttpResponse

#: The instant every fixture's first bar opens. Fixed, so a test's expected
#: timestamps are literals rather than computations.
EPOCH = datetime(2026, 8, 1, 0, 0, tzinfo=timezone.utc)

#: The interval every fixture uses, matching the package default.
INTERVAL = "1h"

#: The provider label every fixture uses, matching the package default.
PROVIDER = "binance-spot"


def instant(hours: int) -> datetime:
    """`EPOCH` plus a whole number of hours."""
    return EPOCH + timedelta(hours=hours)


def crypto_benchmark(
    benchmark_id: str = "BTC",
    *,
    symbol: str = "BTCUSDT",
    display_name: str | None = None,
    quote_unit: str = "USDT",
    schedule: TradingSchedule = TradingSchedule.CONTINUOUS,
) -> Benchmark:
    """One supported, continuously traded market."""
    return Benchmark(
        benchmark_id=benchmark_id,
        display_name=display_name or f"{benchmark_id} market",
        category=MarketCategory.CRYPTO,
        schedule=schedule,
        quote_unit=quote_unit,
        instrument=ProviderInstrument(
            provider=PROVIDER, symbol=symbol, interval=INTERVAL
        ),
    )


def dark_benchmark(
    benchmark_id: str = "DXY",
    *,
    display_name: str | None = None,
    quote_unit: str = "index points",
    category: MarketCategory = MarketCategory.CURRENCY,
    schedule: TradingSchedule = TradingSchedule.SESSION_BOUND,
) -> Benchmark:
    """One market with no configured provider."""
    return Benchmark(
        benchmark_id=benchmark_id,
        display_name=display_name or f"{benchmark_id} index",
        category=category,
        schedule=schedule,
        quote_unit=quote_unit,
        unsupported_reason="no provider is configured for this market",
    )


def universe_of(*benchmarks: Benchmark, name: str = "test") -> MarketUniverse:
    return MarketUniverse(name=name, benchmarks=tuple(benchmarks))


def candles(
    values: list[float],
    *,
    symbol: str = "BTCUSDT",
    interval: str = INTERVAL,
    closed: bool = True,
    start_hour: int = 0,
) -> CandleSeries:
    """A candle series whose closes are exactly ``values``.

    High and low are set to the close so no candle invariant constrains the
    values a test wants — this suite measures closes and nothing else.
    """
    return CandleSeries(
        symbol=symbol,
        timeframe=interval,
        candles=tuple(
            Candle(
                timestamp=instant(start_hour + index),
                symbol=symbol,
                timeframe=interval,
                open=value,
                high=value,
                low=value,
                close=value,
                volume=1.0,
                is_closed=closed,
            )
            for index, value in enumerate(values)
        ),
    )


def observations(
    values: list[float],
    *,
    series_id: str = "binance-spot BTCUSDT 1h",
    start_hour: int = 0,
    unit: str = "price",
) -> ObservationSeries:
    """An observation series whose values are exactly ``values``."""
    return ObservationSeries(
        series_id=series_id,
        unit=unit,
        frequency=INTERVAL,
        timestamps=tuple(
            instant(start_hour + index) for index in range(len(values))
        ),
        values=tuple(values),
    )


def linear(base: float, step: float, count: int) -> list[float]:
    """``count`` prices walking from ``base`` by ``step`` each bar.

    A stated rule rather than a random walk: every figure a test asserts can be
    derived by hand from these three numbers, and a mutation survivor can be
    attributed to a specific arithmetic change rather than to noise.
    """
    return [base + step * index for index in range(count)]


def linear_klines(
    base: float, step: float, count: int, *, start_hour: int = 0
) -> list[list]:
    """Binance kline rows whose closes walk linearly. The adapter's own shape."""
    rows: list[list] = []
    for index in range(count):
        opened = instant(start_hour + index)
        closes_at = instant(start_hour + index + 1)
        price = base + step * index
        rows.append(
            [
                int(opened.timestamp() * 1000),
                f"{price:.8f}",
                f"{price:.8f}",
                f"{price:.8f}",
                f"{price:.8f}",
                "1.0",
                int(closes_at.timestamp() * 1000) - 1,
                "0",
                0,
                "0",
                "0",
                "0",
            ]
        )
    return rows


def ok_response(rows: list[list]) -> HttpResponse:
    return HttpResponse(status=200, body=json.dumps(rows).encode())


def error_response(
    message: str = "Invalid symbol.", *, code: int = -1121, status: int = 400
) -> HttpResponse:
    return HttpResponse(
        status=status, body=json.dumps({"code": code, "msg": message}).encode()
    )


def transport_for(responses: dict[str, HttpResponse]):
    """A `Transport` answering per provider symbol, recording what was asked.

    The returned callable carries a ``calls`` list, which is how the suite
    proves one market is fetched exactly once and an unsupported market is never
    fetched at all.
    """
    calls: list[str] = []

    def send(url: str) -> HttpResponse:
        symbol = url.split("symbol=")[1].split("&")[0]
        calls.append(symbol)
        found = responses.get(symbol)
        if found is None:
            return error_response(f"no fixture for {symbol}")
        return found

    send.calls = calls  # type: ignore[attr-defined]
    return send
